-- --STOCK SUFFISANT → COMMANDE ACCEPTÉE

-- BEGIN
--     INSERT INTO COMMANDE
--     VALUES (
--         SEQ_COMMANDE.NEXTVAL,
--         SYSDATE,
--         '10:00',
--         'En preparation',
--         'EN BOUTIQUE',
--         IDCLIENT
--     );

--     SELECT PRIXVENTEVRAC
--     INTO prixUnit
--     FROM VRAC
--     WHERE IDPRODUIT = IDPRODUIT
--     FOR UPDATE;

--     SELECT IDLOTPRODUIT
--     INTO idLot
--     FROM LOT_PRODUIT
--     WHERE IDPRODUIT = IDPRODUIT
--       AND DATEPEREMPTION > SYSDATE
--     ORDER BY DATEPEREMPTION
--     FETCH FIRST 1 ROW ONLY
--     FOR UPDATE;

--     INSERT INTO LIGNE_COMMANDE
--     VALUES (
--         SEQ_COMMANDE.CURRVAL,
--         1,
--         IDPRODUIT,
--         QUANTITE,
--         'Kg',
--         prixUnit,
--         prixUnit * QUANTITE
--     );
--     UPDATE LOT_PRODUIT
--     SET QUANTITESTOCKLOT = QUANTITESTOCKLOT - QUANTITE
--     WHERE IDLOTPRODUIT = idLot;
--     COMMIT;
-- END;
-- /




-- -- STOCK INSUFFISANT → COMMANDE ANNULÉE
-- BEGIN
--     SELECT SUM(QUANTITESTOCKLOT)
--     FROM LOT_PRODUIT
--     WHERE IDPRODUIT = IDPRODUIT
--       AND DATEPEREMPTION > SYSDATE;
--     ROLLBACK;
-- END;
-- /



-- -- PRODUIT HORS SAISON → COMMANDE REFUSÉ
-- BEGIN
--     SELECT COUNT(*)
--     FROM PERIODE P
--     JOIN PERIODE_DISPONIBILITE PD ON P.IDPERIODE = PD.IDPERIODE
--     WHERE PD.IDPRODUIT = IDPRODUIT
--       AND SYSDATE BETWEEN P.DEBUTPERIODE AND P.FINPERIODE;
--     ROLLBACK;
-- END;
-- /

