-- FONCTIONNALITÉ 2 (ALERTES ET AJUSTEMENT DES PRIX) 

-- CONSULTATION DES ALERTES (Non transactionnel, lecture seule)
SELECT lp.IDLOTPRODUIT, p.NOMPRODUIT, lp.QUANTITESTOCKLOT, lp.DATEPEREMPTION
FROM LOT_PRODUIT lp
JOIN PRODUIT p ON lp.IDPRODUIT = p.IDPRODUIT
WHERE lp.DATEPEREMPTION BETWEEN SYSDATE AND SYSDATE + 7
ORDER BY lp.DATEPEREMPTION ASC;

--  AJUSTEMENT DES PRIX EN VRAC
--  Mise à jour du prix de vente pour chaque produit en vrac concerné
UPDATE VRAC
SET PRIXVENTEVRAC = PRIXVENTEVRAC * (1 - (:pourcentage / 100.0))
WHERE IDPRODUIT = :idProduit;

COMMIT;