
-- SUPPRESSION DES TABLES ET SEQUENCES
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PRODUIT_PERDU CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CONTENANT_PERDU CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PERTE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE RESERVATION_STOCK CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE LOT_CONTENANT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE LOT_PRODUIT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PERIODE_DISPONIBILITE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CONDITIONNEMENT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE POSSEDE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE COORDONNEEPRODUCTEUR CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CARACTERISTIQUE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PRECOND CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE VRAC CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE LIGNE_COMMANDE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE LIVRAISON_DOMICILE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE RETRAIT_BOUTIQUE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE COMMANDE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE STATUT_COMMANDE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ADRESSE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE INFORMATION_CLIENT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CLIENT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CONTENANT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PERIODE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PRODUIT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ACTIVITE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PRODUCTEUR CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COMMANDE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_RETRAIT_BOUTIQUE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_LIVRAISON_DOMICILE';
EXCEPTION WHEN OTHERS THEN NULL; END;
/


-- CREATION DES TABLES
CREATE TABLE PRODUCTEUR (
    IDPRODUCTEUR NUMBER PRIMARY KEY NOT NULL,
    NOMPRODUCTEUR VARCHAR2(100) NOT NULL,
    ADRPRODUCTEUR VARCHAR2(100),
    LATITUDE NUMBER,
    LONGITUDE NUMBER
);

CREATE TABLE COORDONNEEPRODUCTEUR (
    IDPRODUCTEUR NUMBER NOT NULL,
    COORDONNEEPRODUCTEUR VARCHAR2(100) NOT NULL,
    VALEURCOORDONNEE VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_COORDONNEEPRODUCTEUR PRIMARY KEY (IDPRODUCTEUR, COORDONNEEPRODUCTEUR),
    CONSTRAINT FK_COORDPROD_PRODUCTEUR FOREIGN KEY (IDPRODUCTEUR)
        REFERENCES PRODUCTEUR(IDPRODUCTEUR) ON DELETE CASCADE
);

CREATE TABLE ACTIVITE (
    TYPEACTIVITE VARCHAR2(50) PRIMARY KEY
);

CREATE TABLE POSSEDE (
    TYPEACTIVITE VARCHAR2(50),
    IDPRODUCTEUR NUMBER,
    PRIMARY KEY (TYPEACTIVITE, IDPRODUCTEUR),
    FOREIGN KEY (TYPEACTIVITE) REFERENCES ACTIVITE(TYPEACTIVITE) ON DELETE CASCADE,
    FOREIGN KEY (IDPRODUCTEUR) REFERENCES PRODUCTEUR(IDPRODUCTEUR) ON DELETE CASCADE
);

CREATE TABLE PRODUIT (
    IDPRODUIT NUMBER PRIMARY KEY,
    NOMPRODUIT VARCHAR2(100) NOT NULL,
    CATEGORIEPRODUIT VARCHAR2(100),
    DESCRIPT VARCHAR2(300),
    IDPRODUCTEUR NUMBER NOT NULL,
    FOREIGN KEY (IDPRODUCTEUR) REFERENCES PRODUCTEUR(IDPRODUCTEUR)
);

CREATE TABLE CONDITIONNEMENT (
    IDPRODUIT NUMBER NOT NULL,
    TYPECOND VARCHAR2(10) CHECK (TYPECOND IN ('VRAC','PRE')),
    PRIMARY KEY (IDPRODUIT, TYPECOND),
    FOREIGN KEY (IDPRODUIT) REFERENCES PRODUIT(IDPRODUIT) ON DELETE CASCADE
);

CREATE TABLE CARACTERISTIQUE (
    IDPRODUIT NUMBER,
    NOMCARACTERISTIQUE VARCHAR2(100),
    VALCARACTERISTIQUE VARCHAR2(200),
    PRIMARY KEY (IDPRODUIT, NOMCARACTERISTIQUE),
    FOREIGN KEY (IDPRODUIT) REFERENCES PRODUIT(IDPRODUIT) ON DELETE CASCADE
);

CREATE TABLE VRAC (
    IDPRODUIT NUMBER PRIMARY KEY,
    PRIXACHATVRAC NUMBER,
    PRIXKGVRAC NUMBER,
    PRIXVENTEVRAC NUMBER,
    FOREIGN KEY (IDPRODUIT) REFERENCES PRODUIT(IDPRODUIT) ON DELETE CASCADE
);

CREATE TABLE PRECOND (
    IDPRODUIT NUMBER PRIMARY KEY,
    POIDSFIXE NUMBER,
    PRIXACHATP NUMBER,
    PRIXVENTEP NUMBER,
    FOREIGN KEY (IDPRODUIT) REFERENCES PRODUIT(IDPRODUIT) ON DELETE CASCADE
);

CREATE TABLE PERIODE (
    IDPERIODE NUMBER PRIMARY KEY,
    DEBUTPERIODE DATE NOT NULL,
    FINPERIODE DATE NOT NULL,
    CONSTRAINT VERIFDATE CHECK (DEBUTPERIODE < FINPERIODE)
);

CREATE TABLE PERIODE_DISPONIBILITE (
    IDPRODUIT NUMBER,
    IDPERIODE NUMBER,
    PRIMARY KEY (IDPRODUIT, IDPERIODE),
    FOREIGN KEY (IDPRODUIT) REFERENCES PRODUIT(IDPRODUIT) ON DELETE CASCADE,
    FOREIGN KEY (IDPERIODE) REFERENCES PERIODE(IDPERIODE) ON DELETE CASCADE
);

CREATE TABLE CONTENANT (
    IDCONTENANT NUMBER PRIMARY KEY,
    TYPECONTENANT VARCHAR2(50),
    CAPACCONTENANT NUMBER,
    UNITECONTENANT VARCHAR2(10) CHECK (UNITECONTENANT IN ('LITRE','GRAMME')),
    STOCKDISPOCONTENANT NUMBER,
    CARACTCONTENANT VARCHAR2(50) CHECK (CARACTCONTENANT IN ('JETABLE','REUTILISABLE')),
    PRIXVENTECONTENANT  NUMBER
);

CREATE TABLE LOT_PRODUIT (
    IDLOTPRODUIT NUMBER PRIMARY KEY,
    IDPRODUIT NUMBER NOT NULL,
    QUANTITESTOCKLOT  NUMBER,
    UNITESTOCKLOT VARCHAR2(20) CHECK (UNITESTOCKLOT IN ('Kg','Unite')),
    DATERECEPTION DATE,
    DATEPEREMPTION DATE,
    TYPEDATE VARCHAR2(10) NOT NULL CHECK (TYPEDATE IN ('DLC','DLUO')),
    FOREIGN KEY (IDPRODUIT) REFERENCES PRODUIT(IDPRODUIT) ON DELETE CASCADE,
    CONSTRAINT LOTPRODUITDATE CHECK (DATEPEREMPTION >= DATERECEPTION),
    CONSTRAINT LOTPRODUIT_DLC_DLUO_XOR CHECK (
        (TYPEDATE = 'DLC' AND DATEPEREMPTION IS NOT NULL)
            OR
        (TYPEDATE = 'DLUO' AND DATEPEREMPTION IS NOT NULL)
        ),
    -- Hypothèse du sujet : au plus une livraison par jour et par produit
    CONSTRAINT LOTPRODUIT_UNQ_JOUR UNIQUE (IDPRODUIT, DATERECEPTION)
    
);

CREATE TABLE LOT_CONTENANT (
    IDLOTCONTENANT NUMBER PRIMARY KEY,
    IDCONTENANT NUMBER NOT NULL,
    QUANTITESTOCKLOT NUMBER,
    DATERECEPTION DATE,
    FOREIGN KEY (IDCONTENANT) REFERENCES CONTENANT(IDCONTENANT) ON DELETE CASCADE
);

CREATE TABLE PERTE (
    IDPERTE NUMBER PRIMARY KEY,
    ELEMPERDU VARCHAR2(20),
    NATUREPERTE VARCHAR2(50),
    DATEPERTE DATE,
    QUANTITEPERTE NUMBER
);

CREATE TABLE PRODUIT_PERDU (
    IDPRODUIT NUMBER,
    IDPERTE NUMBER,
    PRIMARY KEY (IDPRODUIT, IDPERTE),
    FOREIGN KEY (IDPRODUIT) REFERENCES PRODUIT(IDPRODUIT) ON DELETE CASCADE,
    FOREIGN KEY (IDPERTE) REFERENCES PERTE(IDPERTE) ON DELETE CASCADE
);

CREATE TABLE CONTENANT_PERDU (
    IDCONTENANT NUMBER,
    IDPERTE NUMBER,
    PRIMARY KEY (IDCONTENANT, IDPERTE),
    FOREIGN KEY (IDCONTENANT) REFERENCES CONTENANT(IDCONTENANT) ON DELETE CASCADE,
    FOREIGN KEY (IDPERTE) REFERENCES PERTE(IDPERTE) ON DELETE CASCADE
);

CREATE TABLE CLIENT (
    IDCLIENT NUMBER PRIMARY KEY,
    ANONYME  NUMBER DEFAULT 1,
    CONSTRAINT CLIENT_ANONYME_CK CHECK (ANONYME IN (0,1))
);

CREATE TABLE INFORMATION_CLIENT (
    EMAILCLIENT VARCHAR2(100) PRIMARY KEY,
    NOMCLIENT VARCHAR2(100),
    PRENOMCLIENT VARCHAR2(100),
    NUMTELCLIENT VARCHAR2(40),
    IDCLIENT NUMBER ,
    CONSTRAINT INFCLIENT UNIQUE (IdClient),
    FOREIGN KEY (IDCLIENT) REFERENCES CLIENT(IDCLIENT) ON DELETE CASCADE
);

CREATE TABLE ADRESSE (
    IDADRESSE NUMBER PRIMARY KEY NOT NULL,
    ADRESSEPOSTALE VARCHAR2(200),
    VILLE VARCHAR2(100),
    RUE VARCHAR2(100),
    PAYS  VARCHAR2(80),
    IDCLIENT NUMBER NOT NULL,
    FOREIGN KEY (IDCLIENT) REFERENCES CLIENT(IDCLIENT) ON DELETE CASCADE
);

CREATE TABLE STATUT_COMMANDE (
    STATUT VARCHAR2(30) PRIMARY KEY
);

INSERT INTO STATUT_COMMANDE VALUES ('En preparation');
INSERT INTO STATUT_COMMANDE VALUES ('Prete');
INSERT INTO STATUT_COMMANDE VALUES ('En livraison');
INSERT INTO STATUT_COMMANDE VALUES ('Recupere');
INSERT INTO STATUT_COMMANDE VALUES ('Livree');
INSERT INTO STATUT_COMMANDE VALUES ('Annulee');

CREATE TABLE COMMANDE (
    IDCOMMANDE    NUMBER PRIMARY KEY,
    DATECOMMANDE  DATE,
    HEURECOMMANDE VARCHAR2(12),
    STATUT VARCHAR2(30),
    MODEPAIEMENT  VARCHAR2(20)
        CHECK (MODEPAIEMENT IN ('EN LIGNE','EN BOUTIQUE')),
    IDCLIENT NUMBER NOT NULL,
    FOREIGN KEY (IDCLIENT) REFERENCES CLIENT(IDCLIENT),
    CONSTRAINT VERIFSTATUT CHECK (
        STATUT IN ('En preparation', 'Prete', 'En livraison', 'Recupere', 'Livree', 'Annulee')
    ),
    FOREIGN KEY (STATUT) REFERENCES STATUT_COMMANDE(STATUT)
);

CREATE TABLE LIGNE_COMMANDE (
    IDCOMMANDE NUMBER NOT NULL,
    IDLIGNECOMMANDE NUMBER,
    IDPRODUIT  NUMBER NOT NULL,
    QUANTITECOMMANDE NUMBER,
    UNITECOMMANDE VARCHAR2(20),
    PRIXUNITAIRE NUMBER,
    SOUSTOTAL NUMBER,
    AVEC_CONTENANT NUMBER DEFAULT 0 CHECK (AVEC_CONTENANT IN (0, 1)),
    PRIMARY KEY (IDCOMMANDE, IDLIGNECOMMANDE),
    FOREIGN KEY (IDCOMMANDE) REFERENCES COMMANDE(IDCOMMANDE),
    FOREIGN KEY (IDPRODUIT) REFERENCES PRODUIT(IDPRODUIT)
);

CREATE TABLE RETRAIT_BOUTIQUE (
    IDRETRAITBOUTIQUE NUMBER PRIMARY KEY NOT NULL,
    IDCOMMANDE NUMBER UNIQUE,
    DATEREELLE DATE,
    FOREIGN KEY (IDCOMMANDE) REFERENCES COMMANDE(IDCOMMANDE)
);

CREATE TABLE LIVRAISON_DOMICILE (
    IDLIVRAISONDOMICILE NUMBER PRIMARY KEY NOT NULL,
    IDCOMMANDE NUMBER UNIQUE,
    FRAISLIVRAISON NUMBER,
    DATELIVRAISONESTIMEE DATE,
    IDADRESSE NUMBER,
    DATEREELLE DATE,
    FOREIGN KEY (IDCOMMANDE) REFERENCES COMMANDE(IDCOMMANDE),
    FOREIGN KEY (IDADRESSE) REFERENCES ADRESSE(IDADRESSE)
);

CREATE TABLE RESERVATION_STOCK (
    IDCOMMANDE NUMBER NOT NULL,
    IDLOTPRODUIT NUMBER NOT NULL,
    QUANTITE NUMBER,
    PRIMARY KEY (IDCOMMANDE, IDLOTPRODUIT),
    FOREIGN KEY (IDCOMMANDE) REFERENCES COMMANDE(IDCOMMANDE),
    FOREIGN KEY (IDLOTPRODUIT) REFERENCES LOT_PRODUIT(IDLOTPRODUIT)
);

-- CREATION DES SEQUENCES UTILISEES PAR LE CODE

CREATE SEQUENCE SEQ_COMMANDE START WITH 6 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RETRAIT_BOUTIQUE START WITH 3 INCREMENT BY 1;
CREATE SEQUENCE SEQ_LIVRAISON_DOMICILE START WITH 4 INCREMENT BY 1;


-- INSERTION DES DONNEES

-- Productucteur
INSERT INTO PRODUCTEUR VALUES (1, 'Ferme des Saveurs', '10 Rue des Champs', 45.16, 5.76);
INSERT INTO PRODUCTEUR VALUES (2, 'Miellerie de la Reine', '5 Chemin des Abeilles', 45.18, 5.74);
INSERT INTO PRODUCTEUR VALUES (3, 'Ferme du Val Fleuri', '12 Route du Lac', 45.20, 5.72);
INSERT INTO PRODUCTEUR VALUES (4, 'Les Jardins Verts', '89 Chemin des Pres', 45.22, 5.70);
INSERT INTO PRODUCTEUR VALUES (5, 'La Bergerie Douce', '52 Route des Alpages', 45.24, 5.68);
INSERT INTO PRODUCTEUR VALUES (6, 'Domaine des Grains', '4 Rue des Moissons', 45.26, 5.66);
INSERT INTO PRODUCTEUR VALUES (7, 'Verger Soleil', '21 Avenue des Pommiers', 45.28, 5.64);
INSERT INTO PRODUCTEUR VALUES (8, 'Ferme Champetre', '7 Chemin de la Ferme', 45.30, 5.62);
INSERT INTO PRODUCTEUR VALUES (9, 'Domaine du Ruisseau', '18 Route du Ruisseau', 45.32, 5.60);
INSERT INTO PRODUCTEUR VALUES (10, 'Ferme du Soleil Levant', '33 Rue de la Lune', 45.34, 5.58);

-- Coordonnees producteurs
INSERT INTO COORDONNEEPRODUCTEUR VALUES (3,'TEL','0478123456');
INSERT INTO COORDONNEEPRODUCTEUR VALUES (4,'TEL','0478654321');
INSERT INTO COORDONNEEPRODUCTEUR VALUES (5,'TEL','0478543210');
INSERT INTO COORDONNEEPRODUCTEUR VALUES (8,'TEL','0478001122');
INSERT INTO COORDONNEEPRODUCTEUR VALUES (9,'TEL','0478992211');
INSERT INTO COORDONNEEPRODUCTEUR VALUES (10,'TEL','0478334455');

-- Activites
INSERT INTO ACTIVITE VALUES ('Maraichage');
INSERT INTO ACTIVITE VALUES ('Apiculture');
INSERT INTO ACTIVITE VALUES ('Elevage Ovin');
INSERT INTO ACTIVITE VALUES ('Arboriculture');
INSERT INTO ACTIVITE VALUES ('Céréaliculture');

-- Possede
INSERT INTO POSSEDE VALUES ('Maraichage', 1);
INSERT INTO POSSEDE VALUES ('Apiculture', 2);
INSERT INTO POSSEDE VALUES ('Elevage Ovin', 5);
INSERT INTO POSSEDE VALUES ('Arboriculture', 7);
INSERT INTO POSSEDE VALUES ('Céréaliculture', 6);
INSERT INTO POSSEDE VALUES ('Maraichage', 8);
INSERT INTO POSSEDE VALUES ('Apiculture', 9);
INSERT INTO POSSEDE VALUES ('Maraichage', 10);

-- Clients 
INSERT INTO CLIENT VALUES (1,0);
INSERT INTO CLIENT VALUES (2,0);
INSERT INTO CLIENT VALUES (3,0);

INSERT INTO INFORMATION_CLIENT VALUES ('alice.dupont@mail.fr','Dupont','Alice','0612345678',1);
INSERT INTO INFORMATION_CLIENT VALUES ('bernard.martin@mail.fr','Martin','Bernard','0787654321',2);
INSERT INTO INFORMATION_CLIENT VALUES ('claire.bodin@mail.fr','Bodin','Claire','0601020304',3);

--Adresses
INSERT INTO ADRESSE VALUES (1,'15 Avenue des Cerisiers, Grenoble','Grenoble','Cerisier','France',1);
INSERT INTO ADRESSE VALUES (2,'22 Rue du Château, Grenoble','Grenoble','Château','France',2);
INSERT INTO ADRESSE VALUES (3,'3 Rue des Platanes, Grenoble','Grenoble','Platanes','France',3);

-- Produits 
INSERT INTO PRODUIT VALUES (1,'Pommes de terre','Légume',NULL,1);
INSERT INTO VRAC VALUES (1,0.80,2.50,2.90);

INSERT INTO PRODUIT VALUES (2,'Carottes','Légume',NULL,4);
INSERT INTO VRAC VALUES (2,0.60,1.20,1.50);

INSERT INTO PRODUIT VALUES (3,'Miel de Montagne (500g)','Produit Sucré',NULL,2);
INSERT INTO PRECOND VALUES (3,500,5.00,8.50);

INSERT INTO PRODUIT VALUES (4,'Farine de blé T45','Céréales',NULL,6);
INSERT INTO VRAC VALUES (4,0.50,1.00,1.20);
INSERT INTO PRECOND VALUES (4,1000,1.50,2.50);

INSERT INTO PRODUIT VALUES (5,'Pommes Golden','Fruit',NULL,7);
INSERT INTO VRAC VALUES (5,1.00,2.00,2.50);

INSERT INTO PRODUIT VALUES (6,'Carottes BIO','Légume',NULL,8);
INSERT INTO VRAC VALUES (6,0.80,1.50,1.80);

INSERT INTO PRODUIT VALUES (7,'Miel de Fleurs','Produit Sucré',NULL,9);
INSERT INTO PRECOND VALUES (7,500,4.50,7.50);

INSERT INTO PRODUIT VALUES (8,'Oignons Jaunes','Légume',NULL,1);
INSERT INTO VRAC VALUES (8,0.70,1.40,1.60);

INSERT INTO PRODUIT VALUES (9,'Riz complet','Céréales',NULL,6);
INSERT INTO VRAC VALUES (9,1.50,3.00,3.50);

INSERT INTO PRODUIT VALUES (10,'Farine de Seigle T130','Céréales',NULL,6);
INSERT INTO VRAC VALUES (10,0.75,1.50,1.80);

INSERT INTO PRODUIT VALUES (11,'Fromage de Chèvre (200g)','Produit Laitier',NULL,5);
INSERT INTO PRECOND VALUES (11,200,3.00,5.50);

INSERT INTO PRODUIT VALUES (12,'Confiture de Fraises (300g)','Produit Sucré',NULL,7);
INSERT INTO PRECOND VALUES (12,300,2.50,4.50);

INSERT INTO PRODUIT VALUES (13,'Haricots Verts','Légume',NULL,4);
INSERT INTO VRAC VALUES (13,1.50,3.50,4.00);
INSERT INTO PRECOND VALUES (13,500,2.00,4.50);

INSERT INTO PRODUIT VALUES (14,'Noix (Vrac/Pré)','Fruits Secs',NULL,10);
INSERT INTO VRAC VALUES (14,8.00,16.00,18.00);
INSERT INTO PRECOND VALUES (14,250,5.00,7.00);

INSERT INTO PRODUIT VALUES (15,'Lait Frais (1L)','Produit Laitier',NULL,5);
INSERT INTO PRECOND VALUES (15,1000,1.00,2.00);

INSERT INTO PRODUIT VALUES (16,'Asperges Vertes','Légume',NULL,8);
INSERT INTO VRAC VALUES (16,3.00,6.00,7.50); 

INSERT INTO PRODUIT VALUES (17,'Courgettes','Légume',NULL,10);
INSERT INTO VRAC VALUES (17,0.90,1.80,2.20); 

INSERT INTO PRODUIT VALUES (18,'Noix de Cajou','Fruits Secs',NULL,10);
INSERT INTO VRAC VALUES (18,9.00,18.00,22.00);

INSERT INTO PRODUIT VALUES (19,'Lentilles Vertes','Légumineuse',NULL,6);
INSERT INTO VRAC VALUES (19,1.20,2.40,2.80);

INSERT INTO PRODUIT VALUES (20,'Jus de Pomme (1L)','Boisson',NULL,7);
INSERT INTO PRECOND VALUES (20,1000,1.50,3.00);

-- Conditionnement 
INSERT INTO CONDITIONNEMENT VALUES (1,'VRAC');
INSERT INTO CONDITIONNEMENT VALUES (2,'VRAC');
INSERT INTO CONDITIONNEMENT VALUES (3,'PRE');
INSERT INTO CONDITIONNEMENT VALUES (4,'VRAC');
INSERT INTO CONDITIONNEMENT VALUES (4,'PRE');
INSERT INTO CONDITIONNEMENT VALUES (5,'VRAC');
INSERT INTO CONDITIONNEMENT VALUES (6,'VRAC');
INSERT INTO CONDITIONNEMENT VALUES (7,'PRE');
INSERT INTO CONDITIONNEMENT VALUES (8,'VRAC');
INSERT INTO CONDITIONNEMENT VALUES (9,'VRAC');
INSERT INTO CONDITIONNEMENT VALUES (10,'VRAC');
INSERT INTO CONDITIONNEMENT VALUES (11,'PRE');
INSERT INTO CONDITIONNEMENT VALUES (12,'PRE');
INSERT INTO CONDITIONNEMENT VALUES (13,'VRAC');
INSERT INTO CONDITIONNEMENT VALUES (13,'PRE');
INSERT INTO CONDITIONNEMENT VALUES (14,'VRAC');
INSERT INTO CONDITIONNEMENT VALUES (14,'PRE');
INSERT INTO CONDITIONNEMENT VALUES (15,'PRE');
INSERT INTO CONDITIONNEMENT VALUES (16,'VRAC');
INSERT INTO CONDITIONNEMENT VALUES (17,'VRAC');
INSERT INTO CONDITIONNEMENT VALUES (18,'VRAC');
INSERT INTO CONDITIONNEMENT VALUES (19,'VRAC');
INSERT INTO CONDITIONNEMENT VALUES (20,'PRE');

-- Caracteristiques
INSERT INTO CARACTERISTIQUE VALUES (9, 'Provenance', 'France');
INSERT INTO CARACTERISTIQUE VALUES (15, 'Taux de Matière Grasse', 'Entier');

-- Periode
INSERT INTO PERIODE VALUES (1, DATE '2026-01-01', DATE '2026-03-31');
INSERT INTO PERIODE VALUES (2, DATE '2026-04-01', DATE '2026-06-30'); 
INSERT INTO PERIODE VALUES (3, DATE '2026-07-01', DATE '2026-09-30');
INSERT INTO PERIODE VALUES (4, DATE '2026-10-01', DATE '2026-10-31');
INSERT INTO PERIODE VALUES (5, DATE '2025-11-01', DATE '2025-12-31'); 

-- Periode de disponibilite
INSERT INTO PERIODE_DISPONIBILITE VALUES (1,5); 
INSERT INTO PERIODE_DISPONIBILITE VALUES (2,5); 
INSERT INTO PERIODE_DISPONIBILITE VALUES (4,5); 
INSERT INTO PERIODE_DISPONIBILITE VALUES (5,5); 
INSERT INTO PERIODE_DISPONIBILITE VALUES (6,5); 
INSERT INTO PERIODE_DISPONIBILITE VALUES (8, 5);  
INSERT INTO PERIODE_DISPONIBILITE VALUES (9, 5);  
INSERT INTO PERIODE_DISPONIBILITE VALUES (10, 5); 
INSERT INTO PERIODE_DISPONIBILITE VALUES (11, 5); 
INSERT INTO PERIODE_DISPONIBILITE VALUES (12, 5); 
INSERT INTO PERIODE_DISPONIBILITE VALUES (13, 5); 
INSERT INTO PERIODE_DISPONIBILITE VALUES (14, 5); 
INSERT INTO PERIODE_DISPONIBILITE VALUES (15, 5); 
INSERT INTO PERIODE_DISPONIBILITE VALUES (18, 5); 
INSERT INTO PERIODE_DISPONIBILITE VALUES (19, 5); 
INSERT INTO PERIODE_DISPONIBILITE VALUES (20, 5); 
-- ID 16 Asperges : uniquement en période 2 (Hors saison pour F1 test)
--INSERT INTO PERIODE_DISPONIBILITE VALUES (16,2);

-- LOT PRODUITS (Gestion des stocks pour les tests)

-- ID 1: 
INSERT INTO LOT_PRODUIT VALUES (1,1,50,'Kg',SYSDATE-10,DATE '2026-12-31','DLC');
INSERT INTO LOT_PRODUIT VALUES (2,1,200,'Kg',SYSDATE-20,DATE '2027-03-31','DLC');

-- ID 4: 
INSERT INTO LOT_PRODUIT VALUES (3,4,15,'Kg',SYSDATE-50,DATE '2026-01-30','DLC'); -- Lot 3 (Expire Bientôt)
INSERT INTO LOT_PRODUIT VALUES (4,4,30,'Kg',SYSDATE-10,DATE '2027-02-28','DLC'); -- Lot 4 (Expire Loin)

-- ID 5: 
INSERT INTO LOT_PRODUIT VALUES (6,5,80,'Kg',SYSDATE-3,DATE '2027-05-31','DLC');

-- ID 8: O
INSERT INTO LOT_PRODUIT VALUES (9, 8, 100, 'Kg', SYSDATE-5, DATE '2026-03-31', 'DLC');   -- Lot 9 (Normal)
INSERT INTO LOT_PRODUIT VALUES (15, 8, 20, 'Kg', SYSDATE-1, SYSDATE+5, 'DLC');           -- Lot 15 (PÉREMPTION J+5)

-- ID 14: Noix (Test F1 : Stock juste)
INSERT INTO LOT_PRODUIT VALUES (13, 14, 2.5, 'Kg', SYSDATE-5, DATE '2026-06-30', 'DLUO'); -- Lot 13 (Stock total 2.5 Kg)

-- ID 15: Lait Frais (Test F2 : Péremption proche)
INSERT INTO LOT_PRODUIT VALUES (14, 15, 50, 'Unite', SYSDATE-1, SYSDATE+7, 'DLC');      -- Lot 14 (PÉREMPTION J+7)

-- ID 17: Courgettes (Test F1 : Stock zéro)
-- PAS d'insertion pour le produit ID 17

-- Autres produits
INSERT INTO LOT_PRODUIT VALUES (5,3,100,'Unite',SYSDATE-5,DATE '2027-12-31','DLUO');
INSERT INTO LOT_PRODUIT VALUES (7,6,60,'Kg',SYSDATE-2,DATE '2027-06-30','DLC');
INSERT INTO LOT_PRODUIT VALUES (8,7,120,'Unite',SYSDATE-7,DATE '2027-11-30','DLUO');
INSERT INTO LOT_PRODUIT VALUES (10, 9, 300, 'Kg', SYSDATE-100, DATE '2027-10-01', 'DLUO');
INSERT INTO LOT_PRODUIT VALUES (11, 11, 50, 'Unite', SYSDATE-15, DATE '2026-01-30', 'DLC');
INSERT INTO LOT_PRODUIT VALUES (12, 13, 10, 'Kg', SYSDATE-1, DATE '2026-11-30', 'DLC');
INSERT INTO LOT_PRODUIT VALUES (16, 12, 40, 'Unite', SYSDATE-10, SYSDATE+10, 'DLUO'); -- Test F2 : Péremption J+10 (NON affecté)
INSERT INTO LOT_PRODUIT VALUES (21, 16, 40, 'Kg', SYSDATE-5, SYSDATE+10, 'DLC'); -- Test F2 : Péremption J+10 (NON affecté)

-- CONTENANTS (7 types différents)
INSERT INTO CONTENANT VALUES (1, 'Sachet Papier M', 500, 'GRAMME', 500, 'JETABLE', 0.10);
INSERT INTO CONTENANT VALUES (2, 'Sac Tissu Bio L', 1000, 'GRAMME', 200, 'REUTILISABLE', 2.50);
INSERT INTO CONTENANT VALUES (3, 'Bocal Verre (2L)', 2, 'LITRE', 150, 'REUTILISABLE', 4.50);
INSERT INTO CONTENANT VALUES (4, 'Boite Carton XL', 2000, 'GRAMME', 300, 'JETABLE', 0.50);
INSERT INTO CONTENANT VALUES (5, 'Bouteille 500ml', 0.5, 'LITRE', 100, 'REUTILISABLE', 2.00);
INSERT INTO CONTENANT VALUES (6, 'Bouteille 1L', 1, 'LITRE', 80, 'REUTILISABLE', 3.00);
INSERT INTO CONTENANT VALUES (7, 'Barquette Compostable P', 250, 'GRAMME', 400, 'JETABLE', 0.30);


-- COMMANDES ET LIGNES (Pour Tests F3)

-- COMMANDE ID 1 : Ancienne commande (Déjà Livrée)
INSERT INTO COMMANDE VALUES (1, SYSDATE-2, '10:00:00', 'Livree', 'EN LIGNE', 1);
INSERT INTO LIGNE_COMMANDE VALUES (1,1,1,60,'Kg',2.90,174, 0);
INSERT INTO LIVRAISON_DOMICILE VALUES (1,1,5.00,SYSDATE+2,1,SYSDATE-2); -- Déjà livrée

-- COMMANDE ID 2 : Ancienne commande (Déjà Récupérée)
INSERT INTO COMMANDE VALUES (2, SYSDATE-1, '15:30:00', 'Recupere', 'EN BOUTIQUE', 2);
INSERT INTO LIGNE_COMMANDE VALUES (2,1,4,20,'Kg',1.20,24, 0);
INSERT INTO RETRAIT_BOUTIQUE VALUES (1,2,SYSDATE-1);

-- COMMANDE ID 3 : Nouvelle commande (En préparation, Retrait EN BOUTIQUE) -> TEST F3 SUCCÈS
INSERT INTO COMMANDE VALUES (3, SYSDATE, '11:00:00', 'En preparation', 'EN BOUTIQUE', 3);
INSERT INTO LIGNE_COMMANDE VALUES (3, 1, 9, 5, 'Kg', 3.50, 17.50, 0); -- Riz
INSERT INTO RETRAIT_BOUTIQUE VALUES (2, 3, NULL);

-- COMMANDE ID 4 : Nouvelle commande (En préparation, Livraison EN LIGNE) -> TEST F3 SUCCÈS
INSERT INTO COMMANDE VALUES (4, SYSDATE, '12:00:00', 'En preparation', 'EN LIGNE', 1);
INSERT INTO LIGNE_COMMANDE VALUES (4, 1, 10, 10, 'Kg', 1.80, 18.00, 0); -- Farine Seigle
INSERT INTO LIVRAISON_DOMICILE VALUES (2, 4, 5.00, SYSDATE+2, 1, NULL);

-- COMMANDE ID 5 : Nouvelle commande (Statut Prête) -> Test F3 ECHEC (Statut)
INSERT INTO COMMANDE VALUES (5, SYSDATE-1, '09:00:00', 'Prete', 'EN LIGNE', 2);
INSERT INTO LIGNE_COMMANDE VALUES (5, 1, 13, 2, 'Kg', 4.00, 8.00, 0);
INSERT INTO LIVRAISON_DOMICILE VALUES (3, 5, 5.00, SYSDATE+1, 2, NULL);

 -- =============================================================
-- PRODUIT TECHNIQUE : 999
-- Utilisé comme ligne de produit "factice" pour représenter
-- la vente des contenants dans LIGNE_COMMANDE (logique Java).
-- Le prix réel est porté par la table CONTENANT, pas par ce produit.
-- =============================================================

INSERT INTO PRODUIT VALUES (999,'Contenant','Accessoire',NULL,1);
INSERT INTO PRECOND VALUES (999,1,0.00,0.00); -- Poids et prix unitaires à zéro, le prix est géré par CONTENANT
INSERT INTO CONDITIONNEMENT VALUES (999,'PRE'); -- Conditionnement factice

COMMIT;