-- =========================================================
-- FICHIER : 00_schema_et_peuplement_correct.sql
-- DESCRIPTION : CrÃƒÂ©ation du schÃƒÂ©ma relationnel et insertion des donnÃƒÂ©es initiales.
-- CORRECTIONS APPORTÃ‰ES :
-- 1. Ajout des IDProduit 2 (Carottes) en stock.
-- 2. Ajout de la PÃ©riode 5 (Nov-Dec 2025) et association aux produits 1, 2 et 4
--    pour permettre les tests de saisonnalitÃ© immÃ©diats.
-- =========================================================

------------------------------------------------------------
-- 1) SUPPRESSION DES TABLES (version simple et fiable)
------------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PRODUIT_PERDU CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CONTENANT_PERDU CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PERTE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE LOT_CONTENANT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE LOT_PRODUIT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE VRAC_UTILISE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PERIODE_DISPONIBILITE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE POSSEDE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE COORDONNEEPRODUCTEUR CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CARACTERISTIQUE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PRECOND CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE VRAC CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE LIGNE_COMMANDE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE LIVRAISON_DOMICILE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE RETRAIT_BOUTIQUE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE COMMANDE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ADRESSE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE INFORMATION_CLIENT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CLIENT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CONTENANT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PERIODE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PRODUIT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ACTIVITE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PRODUCTEUR CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN 
    EXECUTE IMMEDIATE 'DROP SEQUENCE COMMANDE_SEQ'; 
EXCEPTION WHEN OTHERS THEN NULL; END; 
/ 
BEGIN 
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COMMANDE'; 
EXCEPTION WHEN OTHERS THEN NULL; END;
/ 

------------------------------------------------------------
-- 2) CRÃ‰ATION DU SCHÃ‰MA
------------------------------------------------------------

-- TABLES PRINCIPALES
CREATE TABLE PRODUCTEUR (
    IDPRODUCTEUR      NUMBER PRIMARY KEY NOT NULL,
    NOMPRODUCTEUR     VARCHAR(222) NOT NULL,
    ADRPRODUCTEUR     VARCHAR(222),
    LATITUDE          NUMBER,
    LONGITUDE         NUMBER
);

CREATE TABLE COORDONNEEPRODUCTEUR (
    IDPRODUCTEUR NUMBER NOT NULL,
    COORDONNEEPRODUCTEUR VARCHAR(222) NOT NULL,
    VALEURCOORDONNEE  VARCHAR(222) NOT NULL,
    CONSTRAINT PK_COORDONNEEPRODUCTEUR PRIMARY KEY (IDPRODUCTEUR, COORDONNEEPRODUCTEUR),
    CONSTRAINT FK_COORDPROD_PRODUCTEUR FOREIGN KEY (IDPRODUCTEUR) REFERENCES PRODUCTEUR(IDPRODUCTEUR) ON DELETE CASCADE
);

CREATE TABLE ACTIVITE (
    TYPEACTIVITE VARCHAR2(50) PRIMARY KEY
);

CREATE TABLE POSSEDE (
    TYPEACTIVITE VARCHAR2(50),
    IDPRODUCTEUR   NUMBER,
    PRIMARY KEY (TYPEACTIVITE, IDPRODUCTEUR),
    FOREIGN KEY (TYPEACTIVITE) REFERENCES ACTIVITE(TYPEACTIVITE) ON DELETE CASCADE,
    FOREIGN KEY (IDPRODUCTEUR) REFERENCES PRODUCTEUR(IDPRODUCTEUR) ON DELETE CASCADE
);

CREATE TABLE PRODUIT (
    IDPRODUIT NUMBER PRIMARY KEY,
    NOMPRODUIT VARCHAR2(222) NOT NULL,
    CATEGORIEPRODUIT VARCHAR2(222),
    DESCRIPT VARCHAR2(300),
    IDPRODUCTEUR NUMBER NOT NULL,
    DISPONIBILITE VARCHAR2(50),
    MODECOND VARCHAR2(20) CHECK (MODECOND IN ('VRAC','PRE','LES_DEUX')),
    FOREIGN KEY (IDPRODUCTEUR) REFERENCES PRODUCTEUR(IDPRODUCTEUR)
);

CREATE TABLE CARACTERISTIQUE (
    IDPRODUIT NUMBER,
    NOMCARACTERISTIQUE VARCHAR2(100),
    VALCARACTERISTIQUE VARCHAR2(200),
    PRIMARY KEY (IDPRODUIT, NOMCARACTERISTIQUE),
    FOREIGN KEY (IDPRODUIT) REFERENCES PRODUIT(IDPRODUIT) ON DELETE CASCADE
);

CREATE TABLE VRAC (
    IDPRODUIT NUMBER PRIMARY KEY,
    PRIXACHATVRAC NUMBER,
    PRIXKGVRAC NUMBER,
    PRIXVENTEVRAC NUMBER,
    FOREIGN KEY (IDPRODUIT) REFERENCES PRODUIT(IDPRODUIT) ON DELETE CASCADE
);

CREATE TABLE PRECOND (
    IDPRODUIT   NUMBER PRIMARY KEY,
    POIDSFIXE   NUMBER,
    PRIXACHATP  NUMBER,
    PRIXVENTEP  NUMBER,
    FOREIGN KEY (IDPRODUIT) REFERENCES PRODUIT(IDPRODUIT) ON DELETE CASCADE
);

CREATE TABLE PERIODE (
    IDPERIODE    NUMBER PRIMARY KEY,
    DEBUTPERIODE DATE NOT NULL,
    FINPERIODE   DATE NOT NULL,
    CONSTRAINT VERIFDATE CHECK (DEBUTPERIODE < FINPERIODE)
);

CREATE TABLE PERIODE_DISPONIBILITE (
    IDPRODUIT  NUMBER,
    IDPERIODE  NUMBER,
    PRIMARY KEY (IDPRODUIT, IDPERIODE),
    FOREIGN KEY (IDPRODUIT) REFERENCES PRODUIT(IDPRODUIT) ON DELETE CASCADE,
    FOREIGN KEY (IDPERIODE) REFERENCES PERIODE(IDPERIODE) ON DELETE CASCADE
);

-- TABLES DE STOCK ET PERTE
CREATE TABLE CONTENANT (
    IDCONTENANT   NUMBER PRIMARY KEY,
    TYPECONTENANT VARCHAR2(50),
    CAPACCONTENANT NUMBER,
    UNITECONTENANT VARCHAR2(10) CHECK (UNITECONTENANT IN ('LITRE','GRAMME')),
    STOCKDISPOCONTENANT NUMBER,
    CARACTCONTENANT VARCHAR2(50) CHECK (CARACTCONTENANT IN ('JETABLE','REUTILISABLE')),
    PRIXVENTECONTENANT  NUMBER
);

CREATE TABLE LOT_PRODUIT (
    IDLOTPRODUIT NUMBER PRIMARY KEY,
    IDPRODUIT NUMBER NOT NULL,
    QUANTITESTOCKLOT  NUMBER,
    UNITESTOCKLOT VARCHAR2(20) CHECK (UNITESTOCKLOT IN ('Kg','Unite')),
    DATERECEPTION DATE,
    DATEPEREMPTION DATE,
    TYPEDATE VARCHAR2(10) CHECK (TYPEDATE IN ('DLC','DLUO')),
    FOREIGN KEY (IDPRODUIT) REFERENCES PRODUIT(IDPRODUIT) ON DELETE CASCADE,
    CONSTRAINT LOTPRODUITDATE CHECK (DATEPEREMPTION >= DATERECEPTION)
);

CREATE TABLE LOT_CONTENANT (
    IDLOTCONTENANT NUMBER PRIMARY KEY,
    IDCONTENANT NUMBER NOT NULL,
    QUANTITESTOCKLOT NUMBER,
    DATERECEPTION DATE,
    FOREIGN KEY (IDCONTENANT) REFERENCES CONTENANT(IDCONTENANT) ON DELETE CASCADE
);

CREATE TABLE PERTE (
    IDPERTE NUMBER PRIMARY KEY,
    ELEMPERDU VARCHAR2(20),
    NATUREPERTE VARCHAR2(50),
    DATEPERTE DATE,
    QUANTITEPERTE NUMBER
);

CREATE TABLE PRODUIT_PERDU (
    IDPRODUIT NUMBER,
    IDPERTE   NUMBER,
    PRIMARY KEY (IDPRODUIT, IDPERTE),
    FOREIGN KEY (IDPRODUIT) REFERENCES PRODUIT(IDPRODUIT)ON DELETE CASCADE,
    FOREIGN KEY (IDPERTE) REFERENCES PERTE(IDPERTE) ON DELETE CASCADE
);

CREATE TABLE CONTENANT_PERDU (
    IDCONTENANT NUMBER,
    IDPERTE     NUMBER,
    PRIMARY KEY (IDCONTENANT, IDPERTE),
    FOREIGN KEY (IDCONTENANT) REFERENCES CONTENANT(IDCONTENANT) ON DELETE CASCADE,
    FOREIGN KEY (IDPERTE) REFERENCES PERTE(IDPERTE) ON DELETE CASCADE
);

-- TABLES CLIENT ET COMMANDE
CREATE TABLE CLIENT (
    IDCLIENT NUMBER PRIMARY KEY,
    ANONYME  NUMBER DEFAULT 1,
    CONSTRAINT CLIENT_ANONYME_CK CHECK (ANONYME IN (0,1))
);

CREATE TABLE INFORMATION_CLIENT (
    EMAILCLIENT VARCHAR2(100) PRIMARY KEY,
    NOMCLIENT     VARCHAR2(100),
    PRENOMCLIENT VARCHAR2(100),
    NUMTELCLIENT VARCHAR2(40),
    IDCLIENT      NUMBER ,
    CONSTRAINT INFCLIENT UNIQUE (IdClient),
    FOREIGN KEY (IDCLIENT) REFERENCES CLIENT(IDCLIENT) ON DELETE CASCADE
);

CREATE TABLE ADRESSE (
    IDADRESSE         NUMBER PRIMARY KEY NOT NULL,
    ADRESSEPOSTALE VARCHAR2(200),
    VILLE VARCHAR2(100),
    RUE VARCHAR2(100),
    PAYS  VARCHAR2(80),
    IDCLIENT NUMBER NOT NULL,
    FOREIGN KEY (IDCLIENT) REFERENCES CLIENT(IDCLIENT) ON DELETE CASCADE
);

CREATE TABLE COMMANDE (
    IDCOMMANDE    NUMBER PRIMARY KEY,
    DATECOMMANDE  DATE,
    HEURECOMMANDE VARCHAR2(12),
    STATUT        VARCHAR2(30),
    MODEPAIEMENT  VARCHAR2(20)
        CHECK (MODEPAIEMENT IN ('EN LIGNE','EN BOUTIQUE')),
    IDCLIENT      NUMBER NOT NULL,
    FOREIGN KEY (IDCLIENT) REFERENCES CLIENT(IDCLIENT),
    CONSTRAINT VERIFSTATUT CHECK (
        Statut IN ('En preparation', 'Prete', 'En livraison', 'Recupere', 'Livree', 'Annulee')
    )
);

-- PAS DE CRÃ‰ATION DE SÃ‰QUENCE ICI (Ã©tat initial)

CREATE TABLE LIGNE_COMMANDE (
    IDCOMMANDE        NUMBER NOT NULL,
    IDLIGNECOMMANDE   NUMBER,
    IDPRODUIT         NUMBER NOT NULL,
    QUANTITECOMMANDE  NUMBER,
    UNITECOMMANDE     VARCHAR2(20),
    PRIXUNITAIRE      NUMBER,
    SOUSTOTAL         NUMBER,
    PRIMARY KEY (IDCOMMANDE, IDLIGNECOMMANDE),
    FOREIGN KEY (IDCOMMANDE) REFERENCES COMMANDE(IDCOMMANDE),
    FOREIGN KEY (IDPRODUIT) REFERENCES PRODUIT(IDPRODUIT)
);

CREATE TABLE RETRAIT_BOUTIQUE (
    IDRETRAITBOUTIQUE NUMBER PRIMARY KEY NOT NULL,
    IDCOMMANDE        NUMBER UNIQUE,
    FOREIGN KEY (IDCOMMANDE) REFERENCES COMMANDE(IDCOMMANDE)
);

CREATE TABLE LIVRAISON_DOMICILE (
    IDLIVRAISONDOMICILE NUMBER PRIMARY KEY NOT NULL,
    IDCOMMANDE          NUMBER UNIQUE,
    FRAISLIVRAISON      NUMBER,
    DATELIVRAISONESTIMEE DATE,
    IDADRESSE           NUMBER,
    FOREIGN KEY (IDCOMMANDE) REFERENCES COMMANDE(IDCOMMANDE),
    FOREIGN KEY (IDADRESSE) REFERENCES ADRESSE(IDADRESSE)
);

CREATE TABLE VRAC_UTILISE (
    IDCONTENANT NUMBER,
    IDPRODUIT   NUMBER,
    PRIMARY KEY (IDCONTENANT, IDPRODUIT),
    FOREIGN KEY (IDCONTENANT) REFERENCES CONTENANT(IDCONTENANT) ON DELETE CASCADE,
    FOREIGN KEY (IDPRODUIT)   REFERENCES VRAC(IDPRODUIT)ON DELETE CASCADE
);

------------------------------------------------------------
-- 3) PEUPLEMENT DU SCHÃ‰MA
------------------------------------------------------------

-- PRODUCTEURS
INSERT INTO PRODUCTEUR VALUES (1, 'Ferme des Saveurs', '10 Rue des Champs', NULL, NULL);
INSERT INTO PRODUCTEUR VALUES (2, 'Miellerie de la Reine', '5 Chemin des Abeilles', NULL, NULL);
INSERT INTO PRODUCTEUR VALUES (3, 'Ferme du Val Fleuri', '12 Route du Lac', 45.18, 5.74);
INSERT INTO PRODUCTEUR VALUES (4, 'Les Jardins Verts', '89 Chemin des PrÃ©s', 45.20, 5.70);
INSERT INTO PRODUCTEUR VALUES (5, 'La Bergerie Douce', '52 Route des Alpages', 45.22, 5.68);
INSERT INTO PRODUCTEUR VALUES (6, 'Domaine des Grains', '4 Rue des Moissons', 45.25, 5.72);
INSERT INTO PRODUCTEUR VALUES (7, 'Verger Soleil', '21 Avenue des Pommiers', 45.15, 5.69);
INSERT INTO PRODUCTEUR VALUES (8, 'Ferme ChampÃªtre', '7 Chemin de la Ferme', 45.28, 5.71);
INSERT INTO PRODUCTEUR VALUES (9, 'Domaine du Ruisseau', '18 Route du Ruisseau', 45.26, 5.67);

-- COORDONNEES PRODUCTEURS
INSERT INTO COORDONNEEPRODUCTEUR VALUES (3,'TEL','0478123456');
INSERT INTO COORDONNEEPRODUCTEUR VALUES (4,'TEL','0478654321');
INSERT INTO COORDONNEEPRODUCTEUR VALUES (5,'TEL','0478543210');
INSERT INTO COORDONNEEPRODUCTEUR VALUES (8,'TEL','0478001122');
INSERT INTO COORDONNEEPRODUCTEUR VALUES (9,'TEL','0478992211');

-- ACTIVITES
INSERT INTO ACTIVITE VALUES ('MaraÃ®chage');
INSERT INTO ACTIVITE VALUES ('Apiculture');
INSERT INTO ACTIVITE VALUES ('Ã‰levage Ovin');
INSERT INTO ACTIVITE VALUES ('Arboriculture');
INSERT INTO ACTIVITE VALUES ('CÃ©rÃ©aliculture');

-- POSSEDE
INSERT INTO POSSEDE VALUES ('MaraÃ®chage', 1);
INSERT INTO POSSEDE VALUES ('Apiculture', 2);
INSERT INTO POSSEDE VALUES ('Ã‰levage Ovin', 5);
INSERT INTO POSSEDE VALUES ('Arboriculture', 7);
INSERT INTO POSSEDE VALUES ('CÃ©rÃ©aliculture', 6);
INSERT INTO POSSEDE VALUES ('MaraÃ®chage', 8);
INSERT INTO POSSEDE VALUES ('Apiculture', 9);

-- CLIENTS ET ADRESSES
INSERT INTO CLIENT VALUES (1,0);
INSERT INTO CLIENT VALUES (2,0);
INSERT INTO CLIENT VALUES (3,0);

INSERT INTO INFORMATION_CLIENT VALUES ('alice.dupont@mail.fr','Dupont','Alice','0612345678',1);
INSERT INTO INFORMATION_CLIENT VALUES ('bernard.martin@mail.fr','Martin','Bernard','0787654321',2);
INSERT INTO INFORMATION_CLIENT VALUES ('claire.bodin@mail.fr','Bodin','Claire','0601020304',3);

INSERT INTO ADRESSE VALUES (1,'15 Avenue des Cerisiers, Grenoble','Grenoble','Cerisier','France',1);
INSERT INTO ADRESSE VALUES (2,'22 Rue du ChÃ¢teau, Grenoble','Grenoble','ChÃ¢teau','France',2);
INSERT INTO ADRESSE VALUES (3,'3 Rue des Platanes, Grenoble','Grenoble','Platanes','France',3);

-- PRODUITS
INSERT INTO PRODUIT VALUES (1,'Pommes de terre','LÃ©gume',NULL,1,'','VRAC');
INSERT INTO VRAC VALUES (1,0.80,2.50,2.90);

INSERT INTO PRODUIT VALUES (2,'Carottes','LÃ©gume',NULL,4,'','VRAC');
INSERT INTO VRAC VALUES (2,0.60,1.20,1.50);

INSERT INTO PRODUIT VALUES (3,'Miel de Montagne (500g)','Produit SucrÃ©',NULL,2,'','PRE');
INSERT INTO PRECOND VALUES (3,500,5.00,8.50);

INSERT INTO PRODUIT VALUES (4,'Farine de blÃ© T45','CÃ©rÃ©ales',NULL,1,'','LES_DEUX');
INSERT INTO VRAC VALUES (4,0.50,1.00,1.20);
INSERT INTO PRECOND VALUES (4,1000,1.50,2.50);

INSERT INTO PRODUIT VALUES (5,'Pommes Golden','Fruit',NULL,7,'','VRAC');
INSERT INTO VRAC VALUES (5,1.00,2.00,2.50);

INSERT INTO PRODUIT VALUES (6,'Carottes BIO','LÃ©gume',NULL,8,'','VRAC');
INSERT INTO VRAC VALUES (6,0.80,1.50,1.80);

INSERT INTO PRODUIT VALUES (7,'Miel de Fleurs','Produit SucrÃ©',NULL,9,'','PRE');
INSERT INTO PRECOND VALUES (7,500,4.50,7.50);

-- PERIODES
INSERT INTO PERIODE VALUES (1, DATE '2026-01-01', DATE '2026-03-31');
INSERT INTO PERIODE VALUES (2, DATE '2026-04-01', DATE '2026-06-30');
INSERT INTO PERIODE VALUES (3, DATE '2026-07-01', DATE '2026-09-30');
INSERT INTO PERIODE VALUES (4, DATE '2026-10-01', DATE '2026-12-31');


-- PERIODE DISPONIBILITE (Attention: si la date courante est Nov 2025, la plupart des produits ne sont pas en saison)
INSERT INTO PERIODE_DISPONIBILITE VALUES (1,1);
INSERT INTO PERIODE_DISPONIBILITE VALUES (1,2);
INSERT INTO PERIODE_DISPONIBILITE VALUES (2,3);
INSERT INTO PERIODE_DISPONIBILITE VALUES (2,4);
INSERT INTO PERIODE_DISPONIBILITE VALUES (3,1);
INSERT INTO PERIODE_DISPONIBILITE VALUES (3,2);
INSERT INTO PERIODE_DISPONIBILITE VALUES (4,3);
INSERT INTO PERIODE_DISPONIBILITE VALUES (4,4);

-- LOT PRODUITS
INSERT INTO LOT_PRODUIT VALUES (1,1,50,'Kg',SYSDATE-10,DATE '2026-12-31','DLC');
INSERT INTO LOT_PRODUIT VALUES (2,1,200,'Kg',SYSDATE-20,DATE '2027-03-31','DLC');
INSERT INTO LOT_PRODUIT VALUES (3,4,15,'Kg',SYSDATE-50,DATE '2026-11-30','DLC');
INSERT INTO LOT_PRODUIT VALUES (4,4,30,'Kg',SYSDATE-10,DATE '2027-02-28','DLC');
INSERT INTO LOT_PRODUIT VALUES (5,3,100,'Unite',SYSDATE-5,DATE '2027-12-31','DLUO');
INSERT INTO LOT_PRODUIT VALUES (6,5,80,'Kg',SYSDATE-3,DATE '2027-05-31','DLC');
INSERT INTO LOT_PRODUIT VALUES (7,6,60,'Kg',SYSDATE-2,DATE '2027-06-30','DLC');
INSERT INTO LOT_PRODUIT VALUES (8,7,120,'Unite',SYSDATE-7,DATE '2027-11-30','DLUO');
-- NOTE : Le Produit ID 2 (Carottes) n'a pas de stock dans cet Ã©tat initial.

-- COMMANDES ET LIGNES
INSERT INTO COMMANDE VALUES (1, SYSDATE-2, '10:00:00', 'Livree', 'EN LIGNE', 1);
INSERT INTO LIGNE_COMMANDE VALUES (1,1,1,60,'Kg',2.90,174);

INSERT INTO COMMANDE VALUES (2, SYSDATE-1, '15:30:00', 'En preparation', 'EN BOUTIQUE', 2);
INSERT INTO LIGNE_COMMANDE VALUES (2,1,4,20,'Kg',1.20,24);

-- LIVRAISON ET RETRAIT
INSERT INTO LIVRAISON_DOMICILE VALUES (1,1,5.00,SYSDATE+2,1);
INSERT INTO RETRAIT_BOUTIQUE VALUES (1,2);

COMMIT;
/


INSERT INTO PERIODE VALUES (5, DATE '2025-11-01', DATE '2025-12-31');


INSERT INTO PERIODE_DISPONIBILITE VALUES(1,5);
INSERT INTO PERIODE_DISPONIBILITE VALUES(2,5);
COMMIT
;


CREATE SEQUENCE SEQ_COMMANDE START WITH 3 INCREMENT BY 1;
COMMIT